FROM python:3.10
WORKDIR /code
COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
COPY ./app /code/app
COPY ./.env /code/.env
EXPOSE 3000
CMD ["fastapi", "run", "app/main.py", "--port", "3000"]
