FROM node:20.17.0
WORKDIR /app
RUN npm install -g pnpm
COPY package.json pnpm-lock.yaml ./
RUN pnpm install
COPY public ./public
COPY src ./src
COPY .eslintrc.json next.config.mjs postcss.config.mjs tailwind.config.ts tsconfig.json ./

COPY .env ./.env
RUN pnpm build
CMD ["pnpm", "start"]